### ISSUE TITLE
Quiet - what is the frequency?

### ISSUE THREAD

**Issue by winster** [quiet/org.quietmodem.Quiet#10]
Hello,

I want to send some text, continuously. So if I call transmitter.send(myData) in a timer task and run it continuously, will it work? Currently receiver is not picking the data

**Comment by brian-armstrong** [comment]
Hi @winster 

Yes, calling transmit with a timer should work.

Which profile are you using? If you use the audible profile, can you hear it transmitting? Can you get the receiver to receive anything?

**Comment by winster** [comment]
Thanks @brian-armstrong. That worked. I used ultrasonic.

Also noticed a problem with an older Android device (Asus - SDK Version 19). There Im getting an issue while setting up receiver.

no.birkett.quietshare W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
no.birkett.quietshare A/libc: Fatal signal 4 (SIGILL) at 0x61ab3825 (code=2), thread 4773 (AudioRecord)

Stackoverflow suggests to reduce the sampling frequency. Any idea how?
