### ISSUE TITLE
Error:error: #endif without #if

### ISSUE THREAD

**Issue by brije111** [quiet/org.quietmodem.Quiet#15]
Right after importing in android studio 3.X.X

**Comment by brije111** [comment]
Thanks for fixing the issue but now I came across one new issue. Now I can't find any 'Run Configuration' available to run this project as an android application.
![screenshot from 2018-01-23 18-13-52](https://user-images.githubusercontent.com/11292348/35276498-98bcb33a-0069-11e8-8818-48e21a9fee42.png)

**Comment by brian-armstrong** [comment]
That's because this isn't an application. It's just a library. If you want to see a sample app using this library, check out https://github.com/alexbirkett/QuietShare
