### ISSUE TITLE
In the given sample sSend.send(p)  throws java.net.NoRouteToHostException

### ISSUE THREAD

**Issue by samirk433** [quiet/org.quietmodem.Quiet#18]
Hello there,
I simply don't understand how this lib works, the documentation isn't good, sorry. Is there any example/demonstration which can be run on both devices (sender, receive; in this case, both are phones).

I tried the given examples, Frame Mode ones worked, it run. But I couldn't send data between devices.
Now, I'm trying the TCP example and it always throws exception; _java.net.NoRouteToHostException: No route to host_.
Can you please help?

**Comment by brian-armstrong** [comment]
Have a look at how the sample app works https://github.com/alexbirkett/QuietShare
