### ISSUE TITLE
Can not build with Android Studio 3.0.+

### ISSUE THREAD

**Issue by alexanderon** [quiet/org.quietmodem.Quiet#23]
Please upgrade the project gradle files compatible with the latest Android Studio version gradle version.

**Comment by brian-armstrong** [comment]
This issue is not descriptive of any errors received

**Comment by brian-armstrong** [comment]
@alexanderon 

I went ahead and tried Android Studio 3 and was able to get the tests passing with Android Studio 3.1.2. Can you give me a description of what failed - what the message was and where it occurred?
