### ISSUE TITLE
how to use the firebase plugins in android studio 3.2.1

### ISSUE THREAD

**Issue by AcharyaPreetham** [quiet/org.quietmodem.Quiet#26]
Im having one project which is developed in Android Studio 2.version now im going to update that software in Android Studio 3.2.1 im getting error like this 

Output:  E:\Barakah_ Admin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:994: error: <item> inner element must either be a resource reference or empty.
E:\Barakah_ Admin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:995: error: <item> inner element must either be a resource reference or empty.
E:\Barakah_ Admin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:996: error: <item> inner element must either be a resource reference or empty.

Command: C:\Users\INTEL\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\89a56138524b25ecc03a2abebe8ccfa7\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        E:\Barakah_ Admin\app\build\intermediates\res\merged\debug \
        E:\Barakah_ Admin\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml

while i press the link it takes me to value.xml file in that i'm not able to edit that lines.

Please any one help me to solve this ISSUE...

**Comment by brian-armstrong** [comment]
I don't think this issue is related to quiet. Please keep issues here related to Quiet issues only. Thanks!
