### ISSUE TITLE
LoopbackFrameReceiver receives data even if the volume is 0

### ISSUE THREAD

**Issue by debu-rnpr** [quiet/org.quietmodem.Quiet#32]
Created a sample activity and implemented the LoopbackFrameReceiver, LoopbackFrameTransmitter. Then I connected my device to a speaker(via Bluetooth) and start the activity received data in the receiver.

I was expecting that no data will be detected as the volume was 0, but it detects how?

**note - I am using the spectrum-analyze app to detect generated sound**

**Comment by brian-armstrong** [comment]
The Loopback device is an entirely virtual device that's there for testing purposes so that tests can run without needing the sound device. It will certainly work even if the volume is 0 since it doesn't ever engage the speaker or mic
