### ISSUE TITLE
How to implement UDP/TCP?

### ISSUE THREAD

**Issue by winster** [quiet/org.quietmodem.Quiet#6]
@brian-armstrong in the usage, I could not see the instance of NetworkInterface being used later. Also what is the significance of 169.254.255.255 ?

**Comment by brian-armstrong** [comment]
@winster Bringing up the NetworkInterface is analogous to running something like `eth up` on Linux. Quiet uses the NetworkInterface to configure the modulation settings and assign a particular IP. When you use the default networking stack (in Java or elsewhere) you do not need to specify which eth is used to send packets. Similarly, Quiet decides which interface to use automatically based on what the udp/tcp appears to be asking for.

169.254.255.255 is the broadcast domain for an auto IP packet (https://tools.ietf.org/html/rfc3927). In other words, it means "send this packet to any interface with an auto IP".

What use case do you have in mind? It may not even be necessary to use the full network interface part of quiet, which does have more complexity involved in development and may be a lot harder to debug/get running at first. On the other hand it can certainly do things that are hard to accomplish just using raw frames.
